# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0002_auto_20150505_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='count',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='corpus',
            name='size',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='date_added',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterUniqueTogether(
            name='countfile',
            unique_together=set([]),
        ),
    ]
