# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0003_auto_20151226_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='label',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
